import AuthProvider from './AuthProvider'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html data-theme="winter" lang="en">
        <body className={montserrat.className}>
          {children}
          <script 
            type='text/javascript' 
            src='../node_modules/tw-elements/dist/js/tw-elements.umd.min.js'>
          </script>
        </body>
      </html>
    </AuthProvider>
  )
}
